name: Node CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Cache NPM downloads
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-npm
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: jgierer12/npm-auth-gpr@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup NPM Registry
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm config set @elseu:registry https://npm.pkg.github.com/
      - name: NPM install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: NPM build
        run: npm run build
      - name: Archive build artifacts
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy_npm:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release'
    needs: [build]
    env:
      BRANCH: ${{ github.ref }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.4
          extra_plugins: semantic-release-slack-bot@1.6.2
        id: semantic
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
